import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "../components/header";

const poppinsSans = Poppins({
  weight: ['100' , '200' , '300' , '400' , '500' , '600' , '700' , '800' , '900'],
  variable: "--font-poppins-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio | Luciano Chiodini",
  description: "Portfolio 2.0 (Luciano Chiodini , yLucino) Generated by NextJS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppinsSans.className} antialiased`}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}